name: Markdown → PDF (privacy + terms)

on:
  push:
    branches: [ master, main ]
    paths:
      - "_pages/privacypolicy.md"
      - "_pages/terms.md"
  workflow_dispatch: {}

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Convert Markdown to PDF and move to _tmp
        run: |
          npx --yes md-to-pdf "_pages/privacypolicy.md"
          npx --yes md-to-pdf "_pages/terms.md"
          mv "_pages/privacypolicy.pdf" "_tmp/privacy-policy.pdf"
          mv "_pages/terms.pdf" "_tmp/terms.pdf"

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: legal-pdfs
          path: _tmp/
