name: Markdown → PDF (privacy + terms)

on:
  push:
    branches: [ master, main ]
    paths:
      - "_pages/privacypolicy.md"
      - "_pages/terms.md"
  workflow_dispatch: {}

jobs:
  build-pdfs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Pandoc + a minimal TeX toolchain for PDF output
      - name: Install Pandoc + TeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-latex-recommended texlive-latex-extra

      - name: Build PDFs into _tmp
        run: |
          # Ensure target dir exists (you said you'll create it, this is just harmless safety)
          mkdir -p _tmp

          # Convert Markdown (supports Jekyll YAML front matter)
          pandoc "_pages/privacypolicy.md" \
            --from=markdown+yaml_metadata_block \
            --pdf-engine=xelatex \
            --toc \
            -o "_tmp/privacy-policy.pdf"

          pandoc "_pages/terms.md" \
            --from=markdown+yaml_metadata_block \
            --pdf-engine=xelatex \
            --toc \
            -o "_tmp/terms.pdf"

      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: legal-pdfs
          path: _tmp/
